export const ADD_BUN: "ADD_BUN" = "ADD_BUN";
export const ADD_INGREDIENT:"ADD_INGREDIENT" = "ADD_INGREDIENT";
export const DELETE_INGREDIENT: "DELETE_INGREDIENT" = "DELETE_INGREDIENT";
export const RESET_CONSTRUCTOR: "RESET_CONSTRUCTOR" = "RESET_CONSTRUCTOR";
export const SWAP_INGREDIENT:"SWAP_INGREDIENT" = "SWAP_INGREDIENT";