export const GET_ORDER_REQUEST: "GET_ORDER_REQUEST" = "GET_ORDER_REQUEST";
export const GET_ORDER_REQUEST_SUCCES: "GET_ORDER_REQUEST_SUCCESS" = "GET_ORDER_REQUEST_SUCCESS";
export const GET_ORDER_REQUEST_FAILED: "GET_ORDER_REQUEST_FAILED" = "GET_ORDER_REQUEST_FAILED";